title: Andrew Barenberg, Ph.D.
description: Faculty Website & Economics Research
theme: jekyll-theme-minimal 
# Note: If you want to restore Chirpy, replace this file with the Chirpy _config.yml and move index.html to a layout.

